@Library('sharedlibrary')_

pipeline {
    environment {
        repoName = sh(script: "basename -s .git ${GIT_URL}", returnStdout: true).trim()
        dockerImage = "227219889473.dkr.ecr.ap-southeast-1.amazonaws.com/${repoName}"
        branchName = sh(script: 'echo $BRANCH_NAME | sed "s#/#-#"', returnStdout: true).trim()
        gitCommit = "${GIT_COMMIT[0..6]}"
        dockerTag = "${branchName}-${gitCommit}"
    }
    
    agent {label 'docker'}
    stages {
        stage('Git Checkout') {
            steps {
                gitCheckout('https://github.com/artisantek/note-project.git', 'main', 'githubCred')
            }
        }

        stage('Docker Build') {
            steps {
                dockerImageBuild('$dockerImage', '$dockerTag')
            }
        }

        stage('Docker Push') {
            steps {
                dockerECRImagePush('$dockerImage', '$dockerTag', 'awsCred', 'ap-southeast-1')
            }
        }

        stage('Kubernetes Deploy - DEV') {
            when {
                anyOf {
                    branch 'development'
                    branch 'feature/*'
                }
            }
            steps {
                kubernetesHelmDeploy('$dockerImage', '$dockerTag', 'note-project', 'awsCred', 'ap-southeast-1', 'eks-cluster', 'dev')
            }
        }

        stage('Kubernetes Deploy - UAT') {        
            when {
                branch 'master_staging'
            }
            steps {
                kubernetesHelmDeploy('$dockerImage', '$dockerTag', 'note-project', 'awsCred', 'ap-southeast-1', 'eks-cluster', 'uat')
            }
        }

        stage('Kubernetes Deploy - PROD') {
            when {
                branch 'master'
            }
            steps {
                kubernetesHelmDeploy('$dockerImage', '$dockerTag', 'note-project', 'awsCred', 'ap-southeast-1', 'eks-cluster', 'prod')
            }
        }

    }
}