apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-project
  template:
    metadata:
      labels:
        app: note-project
    spec:
      containers:
      - image: 227219889473.dkr.ecr.ap-southeast-1.amazonaws.com/note-project:1
        name: note-project
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
        env:
        - name: AWSACCESS
          valueFrom:
            secretKeyRef:
              name: awscred # Name of the secret
              key: AWSACCESS  # Key in the secret
        - name: AWSSECRET
          valueFrom:
            secretKeyRef:
              name: awscred # Name of the secret
              key: AWSSECRET  # Key in the secret
---
apiVersion: v1
kind: Service
metadata:
  name: note-project-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: note-project
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: note-project-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: note-project-svc
            port: 
              number: 8080

