deployment:
  name: note-project
  replicaCount: 1
image:
  account: 227219889473.dkr.ecr.ap-south-1.amazonaws.com
  tag: 1
  containerPort: 8080
service:
  type: ClusterIP
  clusterIPPort: 8080
resource:
  cpu:
    requests: 0.1
    limit: 0.5
  memory:
    requests: 250Mi
    limit: 500Mi
secret:
  name: awscred

